# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gw2info.ui',
# licensing of 'gw2info.ui' applies.
#
# Created: Wed Jan 30 01:45:27 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1347, 854)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBossesStatus = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBossesStatus.setGeometry(QtCore.QRect(350, 10, 381, 461))
        self.groupBossesStatus.setStyleSheet("QGroupBox{\n"
"border: 2px solid gray;\n"
"border-radius: 5px;\n"
"margin-top: 5px; /* leave space at the top for the title */\n"
"}\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top center; /* position at the top center */\n"
"padding: 0 3px;  /* empty space at each side of title */\n"
"}")
        self.groupBossesStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBossesStatus.setObjectName("groupBossesStatus")
        self.label_11 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_11.setGeometry(QtCore.QRect(20, 210, 81, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_13.setGeometry(QtCore.QRect(20, 170, 81, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.lineRaidboss_sabetha = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_sabetha.setGeometry(QtCore.QRect(110, 120, 71, 20))
        self.lineRaidboss_sabetha.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_sabetha.setFrame(False)
        self.lineRaidboss_sabetha.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_sabetha.setReadOnly(True)
        self.lineRaidboss_sabetha.setObjectName("lineRaidboss_sabetha")
        self.label_15 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_15.setGeometry(QtCore.QRect(20, 100, 81, 20))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.lineRaidboss_matthias = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_matthias.setGeometry(QtCore.QRect(110, 210, 71, 20))
        self.lineRaidboss_matthias.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_matthias.setFrame(False)
        self.lineRaidboss_matthias.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_matthias.setReadOnly(True)
        self.lineRaidboss_matthias.setObjectName("lineRaidboss_matthias")
        self.lineRaidboss_valeguardian = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_valeguardian.setGeometry(QtCore.QRect(110, 60, 71, 20))
        self.lineRaidboss_valeguardian.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_valeguardian.setText("")
        self.lineRaidboss_valeguardian.setFrame(False)
        self.lineRaidboss_valeguardian.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_valeguardian.setReadOnly(True)
        self.lineRaidboss_valeguardian.setObjectName("lineRaidboss_valeguardian")
        self.lineRaidboss_keepconstruct = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_keepconstruct.setGeometry(QtCore.QRect(110, 280, 71, 20))
        self.lineRaidboss_keepconstruct.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_keepconstruct.setText("")
        self.lineRaidboss_keepconstruct.setFrame(False)
        self.lineRaidboss_keepconstruct.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_keepconstruct.setReadOnly(True)
        self.lineRaidboss_keepconstruct.setObjectName("lineRaidboss_keepconstruct")
        self.label_17 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_17.setGeometry(QtCore.QRect(20, 120, 81, 20))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_18.setGeometry(QtCore.QRect(20, 280, 81, 20))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.lineRaidboss_slothasor = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_slothasor.setGeometry(QtCore.QRect(110, 170, 71, 20))
        self.lineRaidboss_slothasor.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_slothasor.setText("")
        self.lineRaidboss_slothasor.setFrame(False)
        self.lineRaidboss_slothasor.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_slothasor.setReadOnly(True)
        self.lineRaidboss_slothasor.setObjectName("lineRaidboss_slothasor")
        self.lineRaidboss_gorseval = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_gorseval.setGeometry(QtCore.QRect(110, 100, 71, 20))
        self.lineRaidboss_gorseval.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_gorseval.setText("")
        self.lineRaidboss_gorseval.setFrame(False)
        self.lineRaidboss_gorseval.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_gorseval.setReadOnly(True)
        self.lineRaidboss_gorseval.setObjectName("lineRaidboss_gorseval")
        self.label_19 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_19.setGeometry(QtCore.QRect(20, 60, 81, 20))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.lineRaidboss_xera = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_xera.setGeometry(QtCore.QRect(110, 320, 71, 20))
        self.lineRaidboss_xera.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_xera.setText("")
        self.lineRaidboss_xera.setFrame(False)
        self.lineRaidboss_xera.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_xera.setReadOnly(True)
        self.lineRaidboss_xera.setObjectName("lineRaidboss_xera")
        self.label_20 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_20.setGeometry(QtCore.QRect(20, 320, 81, 20))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_21.setGeometry(QtCore.QRect(10, 370, 91, 20))
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.lineRaidboss_cairn = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_cairn.setGeometry(QtCore.QRect(110, 370, 71, 20))
        self.lineRaidboss_cairn.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_cairn.setText("")
        self.lineRaidboss_cairn.setFrame(False)
        self.lineRaidboss_cairn.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_cairn.setReadOnly(True)
        self.lineRaidboss_cairn.setObjectName("lineRaidboss_cairn")
        self.lineRaidboss_glenna = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_glenna.setGeometry(QtCore.QRect(110, 260, 71, 20))
        self.lineRaidboss_glenna.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_glenna.setText("")
        self.lineRaidboss_glenna.setFrame(False)
        self.lineRaidboss_glenna.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_glenna.setReadOnly(True)
        self.lineRaidboss_glenna.setObjectName("lineRaidboss_glenna")
        self.label_23 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_23.setGeometry(QtCore.QRect(20, 260, 81, 20))
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.lineRaidboss_trio = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_trio.setGeometry(QtCore.QRect(110, 190, 71, 20))
        self.lineRaidboss_trio.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_trio.setText("")
        self.lineRaidboss_trio.setFrame(False)
        self.lineRaidboss_trio.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_trio.setReadOnly(True)
        self.lineRaidboss_trio.setObjectName("lineRaidboss_trio")
        self.label_26 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_26.setGeometry(QtCore.QRect(20, 190, 81, 20))
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_27.setGeometry(QtCore.QRect(10, 40, 171, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_28.setGeometry(QtCore.QRect(10, 390, 91, 20))
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.lineRaidboss_mursaat = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_mursaat.setGeometry(QtCore.QRect(110, 390, 71, 20))
        self.lineRaidboss_mursaat.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_mursaat.setText("")
        self.lineRaidboss_mursaat.setFrame(False)
        self.lineRaidboss_mursaat.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_mursaat.setReadOnly(True)
        self.lineRaidboss_mursaat.setObjectName("lineRaidboss_mursaat")
        self.label_29 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_29.setGeometry(QtCore.QRect(10, 410, 91, 20))
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.lineRaidboss_samarog = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_samarog.setGeometry(QtCore.QRect(110, 410, 71, 20))
        self.lineRaidboss_samarog.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_samarog.setText("")
        self.lineRaidboss_samarog.setFrame(False)
        self.lineRaidboss_samarog.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_samarog.setReadOnly(True)
        self.lineRaidboss_samarog.setObjectName("lineRaidboss_samarog")
        self.label_30 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_30.setGeometry(QtCore.QRect(10, 430, 91, 20))
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.lineRaidboss_deimos = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_deimos.setGeometry(QtCore.QRect(110, 430, 71, 20))
        self.lineRaidboss_deimos.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_deimos.setText("")
        self.lineRaidboss_deimos.setFrame(False)
        self.lineRaidboss_deimos.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_deimos.setReadOnly(True)
        self.lineRaidboss_deimos.setObjectName("lineRaidboss_deimos")
        self.label_31 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_31.setGeometry(QtCore.QRect(10, 150, 171, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.label_34 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_34.setGeometry(QtCore.QRect(10, 240, 171, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_35.setGeometry(QtCore.QRect(10, 350, 171, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.lineRaidboss_twistedcastle = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_twistedcastle.setGeometry(QtCore.QRect(110, 300, 71, 20))
        self.lineRaidboss_twistedcastle.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_twistedcastle.setText("")
        self.lineRaidboss_twistedcastle.setFrame(False)
        self.lineRaidboss_twistedcastle.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_twistedcastle.setReadOnly(True)
        self.lineRaidboss_twistedcastle.setObjectName("lineRaidboss_twistedcastle")
        self.label_36 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_36.setGeometry(QtCore.QRect(20, 300, 81, 20))
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.lineRaidboss_spiritwoods = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_spiritwoods.setGeometry(QtCore.QRect(110, 80, 71, 20))
        self.lineRaidboss_spiritwoods.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_spiritwoods.setText("")
        self.lineRaidboss_spiritwoods.setFrame(False)
        self.lineRaidboss_spiritwoods.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_spiritwoods.setReadOnly(True)
        self.lineRaidboss_spiritwoods.setObjectName("lineRaidboss_spiritwoods")
        self.label_37 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_37.setGeometry(QtCore.QRect(20, 80, 81, 20))
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.label_39 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_39.setGeometry(QtCore.QRect(200, 40, 171, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.lineRaidboss_desmina = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_desmina.setGeometry(QtCore.QRect(300, 60, 71, 20))
        self.lineRaidboss_desmina.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_desmina.setText("")
        self.lineRaidboss_desmina.setFrame(False)
        self.lineRaidboss_desmina.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_desmina.setReadOnly(True)
        self.lineRaidboss_desmina.setObjectName("lineRaidboss_desmina")
        self.label_40 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_40.setGeometry(QtCore.QRect(200, 60, 91, 20))
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.lineRaidboss_riverofsouls = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_riverofsouls.setGeometry(QtCore.QRect(300, 80, 71, 20))
        self.lineRaidboss_riverofsouls.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_riverofsouls.setText("")
        self.lineRaidboss_riverofsouls.setFrame(False)
        self.lineRaidboss_riverofsouls.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_riverofsouls.setReadOnly(True)
        self.lineRaidboss_riverofsouls.setObjectName("lineRaidboss_riverofsouls")
        self.label_41 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_41.setGeometry(QtCore.QRect(200, 80, 91, 20))
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_42.setGeometry(QtCore.QRect(200, 100, 91, 20))
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.lineRaidboss_statues = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_statues.setGeometry(QtCore.QRect(300, 100, 71, 20))
        self.lineRaidboss_statues.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_statues.setText("")
        self.lineRaidboss_statues.setFrame(False)
        self.lineRaidboss_statues.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_statues.setReadOnly(True)
        self.lineRaidboss_statues.setObjectName("lineRaidboss_statues")
        self.lineRaidboss_dhuum = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_dhuum.setGeometry(QtCore.QRect(300, 120, 71, 20))
        self.lineRaidboss_dhuum.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_dhuum.setText("")
        self.lineRaidboss_dhuum.setFrame(False)
        self.lineRaidboss_dhuum.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_dhuum.setReadOnly(True)
        self.lineRaidboss_dhuum.setObjectName("lineRaidboss_dhuum")
        self.label_43 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_43.setGeometry(QtCore.QRect(200, 120, 91, 20))
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.label_47 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_47.setGeometry(QtCore.QRect(200, 150, 171, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.lineRaidboss_conjureda = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_conjureda.setGeometry(QtCore.QRect(300, 170, 71, 20))
        self.lineRaidboss_conjureda.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_conjureda.setText("")
        self.lineRaidboss_conjureda.setFrame(False)
        self.lineRaidboss_conjureda.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_conjureda.setReadOnly(True)
        self.lineRaidboss_conjureda.setObjectName("lineRaidboss_conjureda")
        self.label_48 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_48.setGeometry(QtCore.QRect(200, 190, 91, 20))
        self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_49.setGeometry(QtCore.QRect(200, 210, 91, 20))
        self.label_49.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName("label_49")
        self.lineRaidboss_twinlargos = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_twinlargos.setGeometry(QtCore.QRect(300, 190, 71, 20))
        self.lineRaidboss_twinlargos.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_twinlargos.setText("")
        self.lineRaidboss_twinlargos.setFrame(False)
        self.lineRaidboss_twinlargos.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_twinlargos.setReadOnly(True)
        self.lineRaidboss_twinlargos.setObjectName("lineRaidboss_twinlargos")
        self.label_50 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_50.setGeometry(QtCore.QRect(200, 170, 91, 20))
        self.label_50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName("label_50")
        self.lineRaidboss_qadim = QtWidgets.QLineEdit(self.groupBossesStatus)
        self.lineRaidboss_qadim.setGeometry(QtCore.QRect(300, 210, 71, 20))
        self.lineRaidboss_qadim.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_qadim.setText("")
        self.lineRaidboss_qadim.setFrame(False)
        self.lineRaidboss_qadim.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_qadim.setReadOnly(True)
        self.lineRaidboss_qadim.setObjectName("lineRaidboss_qadim")
        self.label_51 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_51.setGeometry(QtCore.QRect(10, 20, 171, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.line = QtWidgets.QFrame(self.groupBossesStatus)
        self.line.setGeometry(QtCore.QRect(190, 20, 3, 430))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_52 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_52.setGeometry(QtCore.QRect(200, 20, 171, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.label_68 = QtWidgets.QLabel(self.groupBossesStatus)
        self.label_68.setGeometry(QtCore.QRect(200, 240, 171, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_68.setFont(font)
        self.label_68.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_68.setObjectName("label_68")
        self.checkBosses = QtWidgets.QCheckBox(self.groupBossesStatus)
        self.checkBosses.setGeometry(QtCore.QRect(350, 10, 21, 17))
        self.checkBosses.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBosses.setText("")
        self.checkBosses.setObjectName("checkBosses")
        self.groupChallenges = QtWidgets.QGroupBox(self.centralwidget)
        self.groupChallenges.setGeometry(QtCore.QRect(350, 480, 381, 161))
        self.groupChallenges.setStyleSheet("QGroupBox{\n"
"border: 2px solid gray;\n"
"border-radius: 5px;\n"
"margin-top: 5px; /* leave space at the top for the title */\n"
"}\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top center; /* position at the top center */\n"
"padding: 0 3px;  /* empty space at each side of title */\n"
"}")
        self.groupChallenges.setAlignment(QtCore.Qt.AlignCenter)
        self.groupChallenges.setObjectName("groupChallenges")
        self.lineRaidboss_samarog_cm = QtWidgets.QLineEdit(self.groupChallenges)
        self.lineRaidboss_samarog_cm.setGeometry(QtCore.QRect(110, 110, 71, 20))
        self.lineRaidboss_samarog_cm.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_samarog_cm.setText("")
        self.lineRaidboss_samarog_cm.setFrame(False)
        self.lineRaidboss_samarog_cm.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_samarog_cm.setReadOnly(True)
        self.lineRaidboss_samarog_cm.setObjectName("lineRaidboss_samarog_cm")
        self.lineRaidboss_mursaat_cm = QtWidgets.QLineEdit(self.groupChallenges)
        self.lineRaidboss_mursaat_cm.setGeometry(QtCore.QRect(110, 90, 71, 20))
        self.lineRaidboss_mursaat_cm.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_mursaat_cm.setText("")
        self.lineRaidboss_mursaat_cm.setFrame(False)
        self.lineRaidboss_mursaat_cm.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_mursaat_cm.setReadOnly(True)
        self.lineRaidboss_mursaat_cm.setObjectName("lineRaidboss_mursaat_cm")
        self.label_57 = QtWidgets.QLabel(self.groupChallenges)
        self.label_57.setGeometry(QtCore.QRect(10, 130, 91, 20))
        self.label_57.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.groupChallenges)
        self.label_58.setGeometry(QtCore.QRect(10, 110, 91, 20))
        self.label_58.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_58.setObjectName("label_58")
        self.label_55 = QtWidgets.QLabel(self.groupChallenges)
        self.label_55.setGeometry(QtCore.QRect(10, 90, 91, 20))
        self.label_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.groupChallenges)
        self.label_56.setGeometry(QtCore.QRect(10, 70, 91, 20))
        self.label_56.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_56.setObjectName("label_56")
        self.lineRaidboss_deimos_cm = QtWidgets.QLineEdit(self.groupChallenges)
        self.lineRaidboss_deimos_cm.setGeometry(QtCore.QRect(110, 130, 71, 20))
        self.lineRaidboss_deimos_cm.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_deimos_cm.setText("")
        self.lineRaidboss_deimos_cm.setFrame(False)
        self.lineRaidboss_deimos_cm.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_deimos_cm.setReadOnly(True)
        self.lineRaidboss_deimos_cm.setObjectName("lineRaidboss_deimos_cm")
        self.lineRaidboss_cairn_cm = QtWidgets.QLineEdit(self.groupChallenges)
        self.lineRaidboss_cairn_cm.setGeometry(QtCore.QRect(110, 70, 71, 20))
        self.lineRaidboss_cairn_cm.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_cairn_cm.setText("")
        self.lineRaidboss_cairn_cm.setFrame(False)
        self.lineRaidboss_cairn_cm.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_cairn_cm.setReadOnly(True)
        self.lineRaidboss_cairn_cm.setObjectName("lineRaidboss_cairn_cm")
        self.label_59 = QtWidgets.QLabel(self.groupChallenges)
        self.label_59.setGeometry(QtCore.QRect(10, 50, 91, 20))
        self.label_59.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_59.setObjectName("label_59")
        self.lineRaidboss_keepconstruct_cm = QtWidgets.QLineEdit(self.groupChallenges)
        self.lineRaidboss_keepconstruct_cm.setGeometry(QtCore.QRect(110, 50, 71, 20))
        self.lineRaidboss_keepconstruct_cm.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_keepconstruct_cm.setText("")
        self.lineRaidboss_keepconstruct_cm.setFrame(False)
        self.lineRaidboss_keepconstruct_cm.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_keepconstruct_cm.setReadOnly(True)
        self.lineRaidboss_keepconstruct_cm.setObjectName("lineRaidboss_keepconstruct_cm")
        self.label_62 = QtWidgets.QLabel(self.groupChallenges)
        self.label_62.setGeometry(QtCore.QRect(200, 110, 91, 20))
        self.label_62.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_62.setObjectName("label_62")
        self.label_61 = QtWidgets.QLabel(self.groupChallenges)
        self.label_61.setGeometry(QtCore.QRect(200, 130, 91, 20))
        self.label_61.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_61.setObjectName("label_61")
        self.lineRaidboss_qadim_cm = QtWidgets.QLineEdit(self.groupChallenges)
        self.lineRaidboss_qadim_cm.setGeometry(QtCore.QRect(300, 130, 71, 20))
        self.lineRaidboss_qadim_cm.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_qadim_cm.setText("")
        self.lineRaidboss_qadim_cm.setFrame(False)
        self.lineRaidboss_qadim_cm.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_qadim_cm.setReadOnly(True)
        self.lineRaidboss_qadim_cm.setObjectName("lineRaidboss_qadim_cm")
        self.label_64 = QtWidgets.QLabel(self.groupChallenges)
        self.label_64.setGeometry(QtCore.QRect(200, 70, 91, 20))
        self.label_64.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_64.setObjectName("label_64")
        self.label_63 = QtWidgets.QLabel(self.groupChallenges)
        self.label_63.setGeometry(QtCore.QRect(200, 90, 91, 20))
        self.label_63.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_63.setObjectName("label_63")
        self.lineRaidboss_conjureda_cm = QtWidgets.QLineEdit(self.groupChallenges)
        self.lineRaidboss_conjureda_cm.setGeometry(QtCore.QRect(300, 90, 71, 20))
        self.lineRaidboss_conjureda_cm.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_conjureda_cm.setText("")
        self.lineRaidboss_conjureda_cm.setFrame(False)
        self.lineRaidboss_conjureda_cm.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_conjureda_cm.setReadOnly(True)
        self.lineRaidboss_conjureda_cm.setObjectName("lineRaidboss_conjureda_cm")
        self.lineRaidboss_twinlargos_cm = QtWidgets.QLineEdit(self.groupChallenges)
        self.lineRaidboss_twinlargos_cm.setGeometry(QtCore.QRect(300, 110, 71, 20))
        self.lineRaidboss_twinlargos_cm.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_twinlargos_cm.setText("")
        self.lineRaidboss_twinlargos_cm.setFrame(False)
        self.lineRaidboss_twinlargos_cm.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_twinlargos_cm.setReadOnly(True)
        self.lineRaidboss_twinlargos_cm.setObjectName("lineRaidboss_twinlargos_cm")
        self.lineRaidboss_desmina_cm = QtWidgets.QLineEdit(self.groupChallenges)
        self.lineRaidboss_desmina_cm.setGeometry(QtCore.QRect(300, 50, 71, 20))
        self.lineRaidboss_desmina_cm.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_desmina_cm.setText("")
        self.lineRaidboss_desmina_cm.setFrame(False)
        self.lineRaidboss_desmina_cm.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_desmina_cm.setReadOnly(True)
        self.lineRaidboss_desmina_cm.setObjectName("lineRaidboss_desmina_cm")
        self.lineRaidboss_dhuum_cm = QtWidgets.QLineEdit(self.groupChallenges)
        self.lineRaidboss_dhuum_cm.setGeometry(QtCore.QRect(300, 70, 71, 20))
        self.lineRaidboss_dhuum_cm.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineRaidboss_dhuum_cm.setText("")
        self.lineRaidboss_dhuum_cm.setFrame(False)
        self.lineRaidboss_dhuum_cm.setAlignment(QtCore.Qt.AlignCenter)
        self.lineRaidboss_dhuum_cm.setReadOnly(True)
        self.lineRaidboss_dhuum_cm.setObjectName("lineRaidboss_dhuum_cm")
        self.label_67 = QtWidgets.QLabel(self.groupChallenges)
        self.label_67.setGeometry(QtCore.QRect(180, 20, 191, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_67.setFont(font)
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.line_3 = QtWidgets.QFrame(self.groupChallenges)
        self.line_3.setGeometry(QtCore.QRect(190, 20, 3, 130))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_66 = QtWidgets.QLabel(self.groupChallenges)
        self.label_66.setGeometry(QtCore.QRect(10, 20, 171, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_66.setFont(font)
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.checkChallenges = QtWidgets.QCheckBox(self.groupChallenges)
        self.checkChallenges.setGeometry(QtCore.QRect(350, 10, 21, 17))
        self.checkChallenges.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkChallenges.setText("")
        self.checkChallenges.setObjectName("checkChallenges")
        self.label_65 = QtWidgets.QLabel(self.groupChallenges)
        self.label_65.setGeometry(QtCore.QRect(200, 50, 91, 20))
        self.label_65.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_65.setObjectName("label_65")
        self.groupArcdps = QtWidgets.QGroupBox(self.centralwidget)
        self.groupArcdps.setGeometry(QtCore.QRect(750, 10, 271, 221))
        self.groupArcdps.setStyleSheet("QGroupBox{\n"
"border: 2px solid gray;\n"
"border-radius: 5px;\n"
"margin-top: 5px; /* leave space at the top for the title */\n"
"}\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top center; /* position at the top center */\n"
"padding: 0 3px;  /* empty space at each side of title */\n"
"}")
        self.groupArcdps.setAlignment(QtCore.Qt.AlignCenter)
        self.groupArcdps.setObjectName("groupArcdps")
        self.label_46 = QtWidgets.QLabel(self.groupArcdps)
        self.label_46.setGeometry(QtCore.QRect(10, 21, 241, 20))
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.botonFindfolder = QtWidgets.QPushButton(self.groupArcdps)
        self.botonFindfolder.setGeometry(QtCore.QRect(240, 40, 21, 22))
        self.botonFindfolder.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Images/Iconofolder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonFindfolder.setIcon(icon)
        self.botonFindfolder.setObjectName("botonFindfolder")
        self.lineInstallationFolder = QtWidgets.QLineEdit(self.groupArcdps)
        self.lineInstallationFolder.setGeometry(QtCore.QRect(10, 41, 231, 20))
        self.lineInstallationFolder.setReadOnly(True)
        self.lineInstallationFolder.setObjectName("lineInstallationFolder")
        self.botonArcDps = QtWidgets.QPushButton(self.groupArcdps)
        self.botonArcDps.setGeometry(QtCore.QRect(10, 70, 251, 31))
        self.botonArcDps.setStyleSheet("background-color: rgb(170, 208, 169);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/Images/Script.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonArcDps.setIcon(icon1)
        self.botonArcDps.setIconSize(QtCore.QSize(20, 20))
        self.botonArcDps.setObjectName("botonArcDps")
        self.botonArcDps_mechanics = QtWidgets.QPushButton(self.groupArcdps)
        self.botonArcDps_mechanics.setGeometry(QtCore.QRect(10, 110, 251, 31))
        self.botonArcDps_mechanics.setStyleSheet("background-color: rgb(170, 208, 169);")
        self.botonArcDps_mechanics.setIcon(icon1)
        self.botonArcDps_mechanics.setIconSize(QtCore.QSize(20, 20))
        self.botonArcDps_mechanics.setObjectName("botonArcDps_mechanics")
        self.label_53 = QtWidgets.QLabel(self.groupArcdps)
        self.label_53.setGeometry(QtCore.QRect(10, 140, 251, 31))
        self.label_53.setStyleSheet("color: rgb(111, 111, 111);")
        self.label_53.setTextFormat(QtCore.Qt.RichText)
        self.label_53.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_53.setWordWrap(True)
        self.label_53.setObjectName("label_53")
        self.botonLaunchgame = QtWidgets.QPushButton(self.groupArcdps)
        self.botonLaunchgame.setGeometry(QtCore.QRect(150, 180, 111, 31))
        self.botonLaunchgame.setStyleSheet("background-color: rgb(170, 208, 169);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/Images/Game.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonLaunchgame.setIcon(icon2)
        self.botonLaunchgame.setIconSize(QtCore.QSize(20, 20))
        self.botonLaunchgame.setObjectName("botonLaunchgame")
        self.botonClosegame = QtWidgets.QPushButton(self.groupArcdps)
        self.botonClosegame.setGeometry(QtCore.QRect(10, 180, 111, 31))
        self.botonClosegame.setStyleSheet("background-color: rgb(170, 208, 169);")
        self.botonClosegame.setIcon(icon2)
        self.botonClosegame.setIconSize(QtCore.QSize(20, 20))
        self.botonClosegame.setObjectName("botonClosegame")
        self.groupWebsites = QtWidgets.QGroupBox(self.centralwidget)
        self.groupWebsites.setGeometry(QtCore.QRect(750, 240, 271, 401))
        self.groupWebsites.setStyleSheet("QGroupBox{\n"
"border: 2px solid gray;\n"
"border-radius: 5px;\n"
"margin-top: 5px; /* leave space at the top for the title */\n"
"}\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top center; /* position at the top center */\n"
"padding: 0 3px;  /* empty space at each side of title */\n"
"}")
        self.groupWebsites.setAlignment(QtCore.Qt.AlignCenter)
        self.groupWebsites.setObjectName("groupWebsites")
        self.botonWebsite_dpsreport = QtWidgets.QPushButton(self.groupWebsites)
        self.botonWebsite_dpsreport.setGeometry(QtCore.QRect(10, 60, 121, 31))
        self.botonWebsite_dpsreport.setStyleSheet("background-color: rgb(170, 208, 169);")
        self.botonWebsite_dpsreport.setIconSize(QtCore.QSize(20, 20))
        self.botonWebsite_dpsreport.setObjectName("botonWebsite_dpsreport")
        self.botonWebsite_killproof = QtWidgets.QPushButton(self.groupWebsites)
        self.botonWebsite_killproof.setGeometry(QtCore.QRect(10, 100, 121, 31))
        self.botonWebsite_killproof.setStyleSheet("background-color: rgb(170, 208, 169);")
        self.botonWebsite_killproof.setIconSize(QtCore.QSize(20, 20))
        self.botonWebsite_killproof.setObjectName("botonWebsite_killproof")
        self.botonWebsite_raidar = QtWidgets.QPushButton(self.groupWebsites)
        self.botonWebsite_raidar.setGeometry(QtCore.QRect(140, 60, 121, 31))
        self.botonWebsite_raidar.setStyleSheet("background-color: rgb(170, 208, 169);")
        self.botonWebsite_raidar.setIconSize(QtCore.QSize(20, 20))
        self.botonWebsite_raidar.setObjectName("botonWebsite_raidar")
        self.botonWebsite_builds = QtWidgets.QPushButton(self.groupWebsites)
        self.botonWebsite_builds.setGeometry(QtCore.QRect(10, 140, 121, 31))
        self.botonWebsite_builds.setStyleSheet("background-color: rgb(170, 208, 169);")
        self.botonWebsite_builds.setIconSize(QtCore.QSize(20, 20))
        self.botonWebsite_builds.setObjectName("botonWebsite_builds")
        self.botonWebsite_arcdps = QtWidgets.QPushButton(self.groupWebsites)
        self.botonWebsite_arcdps.setGeometry(QtCore.QRect(10, 20, 121, 31))
        self.botonWebsite_arcdps.setStyleSheet("background-color: rgb(170, 208, 169);")
        self.botonWebsite_arcdps.setIconSize(QtCore.QSize(20, 20))
        self.botonWebsite_arcdps.setObjectName("botonWebsite_arcdps")
        self.botonWebsite_arcdpsmechanics = QtWidgets.QPushButton(self.groupWebsites)
        self.botonWebsite_arcdpsmechanics.setGeometry(QtCore.QRect(140, 20, 121, 31))
        self.botonWebsite_arcdpsmechanics.setStyleSheet("background-color: rgb(170, 208, 169);")
        self.botonWebsite_arcdpsmechanics.setIconSize(QtCore.QSize(20, 20))
        self.botonWebsite_arcdpsmechanics.setObjectName("botonWebsite_arcdpsmechanics")
        self.botonWebsite_dulfy = QtWidgets.QPushButton(self.groupWebsites)
        self.botonWebsite_dulfy.setGeometry(QtCore.QRect(140, 100, 121, 31))
        self.botonWebsite_dulfy.setStyleSheet("background-color: rgb(170, 208, 169);")
        self.botonWebsite_dulfy.setIconSize(QtCore.QSize(20, 20))
        self.botonWebsite_dulfy.setObjectName("botonWebsite_dulfy")
        self.botonWebsite_builds_alternative = QtWidgets.QPushButton(self.groupWebsites)
        self.botonWebsite_builds_alternative.setGeometry(QtCore.QRect(140, 140, 121, 31))
        self.botonWebsite_builds_alternative.setStyleSheet("background-color: rgb(170, 208, 169);")
        self.botonWebsite_builds_alternative.setIconSize(QtCore.QSize(20, 20))
        self.botonWebsite_builds_alternative.setObjectName("botonWebsite_builds_alternative")
        self.label_54 = QtWidgets.QLabel(self.groupWebsites)
        self.label_54.setGeometry(QtCore.QRect(10, 320, 251, 61))
        self.label_54.setStyleSheet("color: rgb(111, 111, 111);")
        self.label_54.setTextFormat(QtCore.Qt.RichText)
        self.label_54.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_54.setWordWrap(True)
        self.label_54.setObjectName("label_54")
        self.label_60 = QtWidgets.QLabel(self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(350, 660, 421, 41))
        self.label_60.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_60.setObjectName("label_60")
        self.groupCurrency = QtWidgets.QGroupBox(self.centralwidget)
        self.groupCurrency.setGeometry(QtCore.QRect(10, 550, 321, 161))
        self.groupCurrency.setStyleSheet("QGroupBox{\n"
"border: 2px solid gray;\n"
"border-radius: 5px;\n"
"margin-top: 5px; /* leave space at the top for the title */\n"
"}\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top center; /* position at the top center */\n"
"padding: 0 3px;  /* empty space at each side of title */\n"
"}")
        self.groupCurrency.setAlignment(QtCore.Qt.AlignCenter)
        self.groupCurrency.setObjectName("groupCurrency")
        self.label_93 = QtWidgets.QLabel(self.groupCurrency)
        self.label_93.setGeometry(QtCore.QRect(10, 90, 141, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_93.setFont(font)
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName("label_93")
        self.label_94 = QtWidgets.QLabel(self.groupCurrency)
        self.label_94.setGeometry(QtCore.QRect(10, 20, 141, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_94.setFont(font)
        self.label_94.setAlignment(QtCore.Qt.AlignCenter)
        self.label_94.setObjectName("label_94")
        self.label_44 = QtWidgets.QLabel(self.groupCurrency)
        self.label_44.setGeometry(QtCore.QRect(10, 50, 131, 20))
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.lineCurrency_Magnetiteshards = QtWidgets.QLineEdit(self.groupCurrency)
        self.lineCurrency_Magnetiteshards.setGeometry(QtCore.QRect(150, 50, 71, 20))
        self.lineCurrency_Magnetiteshards.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineCurrency_Magnetiteshards.setText("")
        self.lineCurrency_Magnetiteshards.setFrame(False)
        self.lineCurrency_Magnetiteshards.setAlignment(QtCore.Qt.AlignCenter)
        self.lineCurrency_Magnetiteshards.setReadOnly(True)
        self.lineCurrency_Magnetiteshards.setObjectName("lineCurrency_Magnetiteshards")
        self.label_45 = QtWidgets.QLabel(self.groupCurrency)
        self.label_45.setGeometry(QtCore.QRect(10, 110, 131, 20))
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.lineCurrency_Gaetingcrystals = QtWidgets.QLineEdit(self.groupCurrency)
        self.lineCurrency_Gaetingcrystals.setGeometry(QtCore.QRect(150, 110, 71, 20))
        self.lineCurrency_Gaetingcrystals.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineCurrency_Gaetingcrystals.setText("")
        self.lineCurrency_Gaetingcrystals.setFrame(False)
        self.lineCurrency_Gaetingcrystals.setAlignment(QtCore.Qt.AlignCenter)
        self.lineCurrency_Gaetingcrystals.setReadOnly(True)
        self.lineCurrency_Gaetingcrystals.setObjectName("lineCurrency_Gaetingcrystals")
        self.label_81 = QtWidgets.QLabel(self.groupCurrency)
        self.label_81.setGeometry(QtCore.QRect(10, 130, 131, 20))
        self.label_81.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_81.setObjectName("label_81")
        self.lineCurrency_Legend_divinations = QtWidgets.QLineEdit(self.groupCurrency)
        self.lineCurrency_Legend_divinations.setGeometry(QtCore.QRect(150, 130, 71, 20))
        self.lineCurrency_Legend_divinations.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineCurrency_Legend_divinations.setText("")
        self.lineCurrency_Legend_divinations.setFrame(False)
        self.lineCurrency_Legend_divinations.setAlignment(QtCore.Qt.AlignCenter)
        self.lineCurrency_Legend_divinations.setReadOnly(True)
        self.lineCurrency_Legend_divinations.setObjectName("lineCurrency_Legend_divinations")
        self.lineCurrency_Legend_insights = QtWidgets.QLineEdit(self.groupCurrency)
        self.lineCurrency_Legend_insights.setGeometry(QtCore.QRect(150, 70, 71, 20))
        self.lineCurrency_Legend_insights.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineCurrency_Legend_insights.setText("")
        self.lineCurrency_Legend_insights.setFrame(False)
        self.lineCurrency_Legend_insights.setAlignment(QtCore.Qt.AlignCenter)
        self.lineCurrency_Legend_insights.setReadOnly(True)
        self.lineCurrency_Legend_insights.setObjectName("lineCurrency_Legend_insights")
        self.label_82 = QtWidgets.QLabel(self.groupCurrency)
        self.label_82.setGeometry(QtCore.QRect(10, 70, 131, 20))
        self.label_82.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_82.setObjectName("label_82")
        self.checkCurrency = QtWidgets.QCheckBox(self.groupCurrency)
        self.checkCurrency.setGeometry(QtCore.QRect(290, 10, 21, 17))
        self.checkCurrency.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkCurrency.setText("")
        self.checkCurrency.setObjectName("checkCurrency")
        self.lineCurrency_Legend_divinations_week = QtWidgets.QLineEdit(self.groupCurrency)
        self.lineCurrency_Legend_divinations_week.setGeometry(QtCore.QRect(240, 130, 71, 20))
        self.lineCurrency_Legend_divinations_week.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineCurrency_Legend_divinations_week.setText("")
        self.lineCurrency_Legend_divinations_week.setFrame(False)
        self.lineCurrency_Legend_divinations_week.setAlignment(QtCore.Qt.AlignCenter)
        self.lineCurrency_Legend_divinations_week.setReadOnly(True)
        self.lineCurrency_Legend_divinations_week.setObjectName("lineCurrency_Legend_divinations_week")
        self.lineCurrency_Gaetingcrystals_week = QtWidgets.QLineEdit(self.groupCurrency)
        self.lineCurrency_Gaetingcrystals_week.setGeometry(QtCore.QRect(240, 110, 71, 20))
        self.lineCurrency_Gaetingcrystals_week.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineCurrency_Gaetingcrystals_week.setText("")
        self.lineCurrency_Gaetingcrystals_week.setFrame(False)
        self.lineCurrency_Gaetingcrystals_week.setAlignment(QtCore.Qt.AlignCenter)
        self.lineCurrency_Gaetingcrystals_week.setReadOnly(True)
        self.lineCurrency_Gaetingcrystals_week.setObjectName("lineCurrency_Gaetingcrystals_week")
        self.lineCurrency_Legend_insights_week = QtWidgets.QLineEdit(self.groupCurrency)
        self.lineCurrency_Legend_insights_week.setGeometry(QtCore.QRect(240, 70, 71, 20))
        self.lineCurrency_Legend_insights_week.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineCurrency_Legend_insights_week.setText("")
        self.lineCurrency_Legend_insights_week.setFrame(False)
        self.lineCurrency_Legend_insights_week.setAlignment(QtCore.Qt.AlignCenter)
        self.lineCurrency_Legend_insights_week.setReadOnly(True)
        self.lineCurrency_Legend_insights_week.setObjectName("lineCurrency_Legend_insights_week")
        self.lineCurrency_Magnetiteshards_week = QtWidgets.QLineEdit(self.groupCurrency)
        self.lineCurrency_Magnetiteshards_week.setGeometry(QtCore.QRect(240, 50, 71, 20))
        self.lineCurrency_Magnetiteshards_week.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.lineCurrency_Magnetiteshards_week.setText("")
        self.lineCurrency_Magnetiteshards_week.setFrame(False)
        self.lineCurrency_Magnetiteshards_week.setAlignment(QtCore.Qt.AlignCenter)
        self.lineCurrency_Magnetiteshards_week.setReadOnly(True)
        self.lineCurrency_Magnetiteshards_week.setObjectName("lineCurrency_Magnetiteshards_week")
        self.label_70 = QtWidgets.QLabel(self.groupCurrency)
        self.label_70.setGeometry(QtCore.QRect(240, 30, 71, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_70.setFont(font)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.label_71 = QtWidgets.QLabel(self.groupCurrency)
        self.label_71.setGeometry(QtCore.QRect(240, 90, 71, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_71.setFont(font)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.groupCurrency)
        self.label_72.setGeometry(QtCore.QRect(150, 90, 71, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_72.setFont(font)
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.groupCurrency)
        self.label_73.setGeometry(QtCore.QRect(150, 30, 71, 20))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_73.setFont(font)
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.groupAPI = QtWidgets.QGroupBox(self.centralwidget)
        self.groupAPI.setGeometry(QtCore.QRect(10, 60, 321, 251))
        self.groupAPI.setStyleSheet("QGroupBox{\n"
"border: 2px solid gray;\n"
"border-radius: 5px;\n"
"margin-top: 5px; /* leave space at the top for the title */\n"
"}\n"
"QGroupBox::title {\n"
"subcontrol-origin: margin;\n"
"subcontrol-position: top center; /* position at the top center */\n"
"padding: 0 3px;  /* empty space at each side of title */\n"
"}")
        self.groupAPI.setAlignment(QtCore.Qt.AlignCenter)
        self.groupAPI.setObjectName("groupAPI")
        self.botonWebsite_Anet = QtWidgets.QPushButton(self.groupAPI)
        self.botonWebsite_Anet.setGeometry(QtCore.QRect(10, 210, 71, 31))
        self.botonWebsite_Anet.setStyleSheet("background-color: rgb(170, 208, 169);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/Images/Browser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonWebsite_Anet.setIcon(icon3)
        self.botonWebsite_Anet.setIconSize(QtCore.QSize(20, 20))
        self.botonWebsite_Anet.setObjectName("botonWebsite_Anet")
        self.label_25 = QtWidgets.QLabel(self.groupAPI)
        self.label_25.setGeometry(QtCore.QRect(10, 20, 201, 20))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.botonLoad = QtWidgets.QPushButton(self.groupAPI)
        self.botonLoad.setGeometry(QtCore.QRect(220, 32, 91, 31))
        self.botonLoad.setStyleSheet("background-color: rgb(170, 208, 169);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/Images/Refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonLoad.setIcon(icon4)
        self.botonLoad.setIconSize(QtCore.QSize(20, 20))
        self.botonLoad.setObjectName("botonLoad")
        self.botonDeleteAPI = QtWidgets.QPushButton(self.groupAPI)
        self.botonDeleteAPI.setGeometry(QtCore.QRect(220, 210, 91, 31))
        self.botonDeleteAPI.setStyleSheet("background-color: rgb(170, 208, 169);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/Images/Delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonDeleteAPI.setIcon(icon5)
        self.botonDeleteAPI.setIconSize(QtCore.QSize(20, 20))
        self.botonDeleteAPI.setObjectName("botonDeleteAPI")
        self.comboSelectAPI = QtWidgets.QComboBox(self.groupAPI)
        self.comboSelectAPI.setGeometry(QtCore.QRect(10, 40, 201, 20))
        self.comboSelectAPI.setObjectName("comboSelectAPI")
        self.label_33 = QtWidgets.QLabel(self.groupAPI)
        self.label_33.setGeometry(QtCore.QRect(10, 150, 301, 51))
        self.label_33.setStyleSheet("color: rgb(111, 111, 111);")
        self.label_33.setTextFormat(QtCore.Qt.RichText)
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_33.setWordWrap(True)
        self.label_33.setObjectName("label_33")
        self.botonAddAPI = QtWidgets.QPushButton(self.groupAPI)
        self.botonAddAPI.setGeometry(QtCore.QRect(90, 210, 121, 31))
        self.botonAddAPI.setStyleSheet("background-color: rgb(170, 208, 169);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/Images/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonAddAPI.setIcon(icon6)
        self.botonAddAPI.setIconSize(QtCore.QSize(20, 20))
        self.botonAddAPI.setObjectName("botonAddAPI")
        self.line_2 = QtWidgets.QFrame(self.groupAPI)
        self.line_2.setGeometry(QtCore.QRect(10, 140, 300, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.linePermission_Characters = QtWidgets.QLineEdit(self.groupAPI)
        self.linePermission_Characters.setGeometry(QtCore.QRect(90, 90, 71, 20))
        self.linePermission_Characters.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.linePermission_Characters.setFrame(False)
        self.linePermission_Characters.setAlignment(QtCore.Qt.AlignCenter)
        self.linePermission_Characters.setReadOnly(True)
        self.linePermission_Characters.setObjectName("linePermission_Characters")
        self.linePermission_Guilds = QtWidgets.QLineEdit(self.groupAPI)
        self.linePermission_Guilds.setGeometry(QtCore.QRect(170, 110, 61, 20))
        self.linePermission_Guilds.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.linePermission_Guilds.setFrame(False)
        self.linePermission_Guilds.setAlignment(QtCore.Qt.AlignCenter)
        self.linePermission_Guilds.setReadOnly(True)
        self.linePermission_Guilds.setObjectName("linePermission_Guilds")
        self.linePermission_PvP = QtWidgets.QLineEdit(self.groupAPI)
        self.linePermission_PvP.setGeometry(QtCore.QRect(240, 70, 71, 20))
        self.linePermission_PvP.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.linePermission_PvP.setFrame(False)
        self.linePermission_PvP.setAlignment(QtCore.Qt.AlignCenter)
        self.linePermission_PvP.setReadOnly(True)
        self.linePermission_PvP.setObjectName("linePermission_PvP")
        self.linePermission_Unlocks = QtWidgets.QLineEdit(self.groupAPI)
        self.linePermission_Unlocks.setGeometry(QtCore.QRect(170, 90, 61, 20))
        self.linePermission_Unlocks.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.linePermission_Unlocks.setFrame(False)
        self.linePermission_Unlocks.setAlignment(QtCore.Qt.AlignCenter)
        self.linePermission_Unlocks.setReadOnly(True)
        self.linePermission_Unlocks.setObjectName("linePermission_Unlocks")
        self.linePermission_Builds = QtWidgets.QLineEdit(self.groupAPI)
        self.linePermission_Builds.setGeometry(QtCore.QRect(240, 90, 71, 20))
        self.linePermission_Builds.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.linePermission_Builds.setFrame(False)
        self.linePermission_Builds.setAlignment(QtCore.Qt.AlignCenter)
        self.linePermission_Builds.setReadOnly(True)
        self.linePermission_Builds.setObjectName("linePermission_Builds")
        self.linePermission_Tradingpost = QtWidgets.QLineEdit(self.groupAPI)
        self.linePermission_Tradingpost.setGeometry(QtCore.QRect(90, 110, 71, 20))
        self.linePermission_Tradingpost.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.linePermission_Tradingpost.setFrame(False)
        self.linePermission_Tradingpost.setAlignment(QtCore.Qt.AlignCenter)
        self.linePermission_Tradingpost.setReadOnly(True)
        self.linePermission_Tradingpost.setObjectName("linePermission_Tradingpost")
        self.linePermission_Inventories = QtWidgets.QLineEdit(self.groupAPI)
        self.linePermission_Inventories.setGeometry(QtCore.QRect(10, 110, 71, 20))
        self.linePermission_Inventories.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.linePermission_Inventories.setFrame(False)
        self.linePermission_Inventories.setAlignment(QtCore.Qt.AlignCenter)
        self.linePermission_Inventories.setReadOnly(True)
        self.linePermission_Inventories.setObjectName("linePermission_Inventories")
        self.linePermission_Progression = QtWidgets.QLineEdit(self.groupAPI)
        self.linePermission_Progression.setGeometry(QtCore.QRect(240, 110, 71, 20))
        self.linePermission_Progression.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.linePermission_Progression.setFrame(False)
        self.linePermission_Progression.setAlignment(QtCore.Qt.AlignCenter)
        self.linePermission_Progression.setReadOnly(True)
        self.linePermission_Progression.setObjectName("linePermission_Progression")
        self.linePermission_Wallet = QtWidgets.QLineEdit(self.groupAPI)
        self.linePermission_Wallet.setGeometry(QtCore.QRect(170, 70, 61, 20))
        self.linePermission_Wallet.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.linePermission_Wallet.setFrame(False)
        self.linePermission_Wallet.setAlignment(QtCore.Qt.AlignCenter)
        self.linePermission_Wallet.setReadOnly(True)
        self.linePermission_Wallet.setObjectName("linePermission_Wallet")
        self.linePermission_Account = QtWidgets.QLineEdit(self.groupAPI)
        self.linePermission_Account.setGeometry(QtCore.QRect(10, 90, 71, 20))
        self.linePermission_Account.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.linePermission_Account.setFrame(False)
        self.linePermission_Account.setAlignment(QtCore.Qt.AlignCenter)
        self.linePermission_Account.setReadOnly(True)
        self.linePermission_Account.setObjectName("linePermission_Account")
        self.label_38 = QtWidgets.QLabel(self.groupAPI)
        self.label_38.setGeometry(QtCore.QRect(10, 61, 151, 20))
        self.label_38.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_38.setObjectName("label_38")
        self.tabUnlocks = QtWidgets.QTabWidget(self.centralwidget)
        self.tabUnlocks.setGeometry(QtCore.QRect(10, 320, 321, 221))
        self.tabUnlocks.setStyleSheet(" /* The tab menu buttons */\n"
"QTabBar::tab {\n"
"    border: 2px solid gray;\n"
"    border-bottom: 0px;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    padding: 2px;}\n"
"\n"
" /* The tab specific buttons */\n"
"QTabBar::tab:selected {border-color: black;background-color: gray;}\n"
"QTabBar::tab:hover {background-color: gray;}\n"
"\n"
" /* The tab widget frame */\n"
"QTabWidget::pane {\n"
"border-radius: 5px;\n"
"border: 2px solid gray;\n"
"}")
        self.tabUnlocks.setObjectName("tabUnlocks")
        self.tab_minis = QtWidgets.QWidget()
        self.tab_minis.setObjectName("tab_minis")
        self.line_5 = QtWidgets.QFrame(self.tab_minis)
        self.line_5.setGeometry(QtCore.QRect(170, 10, 3, 140))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_92 = QtWidgets.QLabel(self.tab_minis)
        self.label_92.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_92.setFont(font)
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName("label_92")
        self.label_91 = QtWidgets.QLabel(self.tab_minis)
        self.label_91.setGeometry(QtCore.QRect(180, 10, 131, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_91.setFont(font)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.checkMinis = QtWidgets.QCheckBox(self.tab_minis)
        self.checkMinis.setGeometry(QtCore.QRect(290, 0, 21, 17))
        self.checkMinis.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkMinis.setText("")
        self.checkMinis.setObjectName("checkMinis")
        self.label_Mini_redguardian = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_redguardian.setGeometry(QtCore.QRect(10, 40, 32, 32))
        self.label_Mini_redguardian.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_redguardian.setText("")
        self.label_Mini_redguardian.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Red Guardian.png"))
        self.label_Mini_redguardian.setScaledContents(True)
        self.label_Mini_redguardian.setObjectName("label_Mini_redguardian")
        self.label_Mini_greenguardian = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_greenguardian.setGeometry(QtCore.QRect(40, 40, 32, 32))
        self.label_Mini_greenguardian.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_greenguardian.setText("")
        self.label_Mini_greenguardian.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Green Guardian.png"))
        self.label_Mini_greenguardian.setScaledContents(True)
        self.label_Mini_greenguardian.setObjectName("label_Mini_greenguardian")
        self.label_Mini_blueguardian = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_blueguardian.setGeometry(QtCore.QRect(70, 40, 32, 32))
        self.label_Mini_blueguardian.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_blueguardian.setText("")
        self.label_Mini_blueguardian.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Blue Guardian.png"))
        self.label_Mini_blueguardian.setScaledContents(True)
        self.label_Mini_blueguardian.setObjectName("label_Mini_blueguardian")
        self.label_Mini_valeguardian = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_valeguardian.setGeometry(QtCore.QRect(100, 40, 32, 32))
        self.label_Mini_valeguardian.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_valeguardian.setText("")
        self.label_Mini_valeguardian.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Vale Guardian.png"))
        self.label_Mini_valeguardian.setScaledContents(True)
        self.label_Mini_valeguardian.setObjectName("label_Mini_valeguardian")
        self.label_Mini_gorseval = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_gorseval.setGeometry(QtCore.QRect(130, 40, 32, 32))
        self.label_Mini_gorseval.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_gorseval.setText("")
        self.label_Mini_gorseval.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Gorseval the Multifarious.png"))
        self.label_Mini_gorseval.setScaledContents(True)
        self.label_Mini_gorseval.setObjectName("label_Mini_gorseval")
        self.label_Mini_knuckles = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_knuckles.setGeometry(QtCore.QRect(10, 70, 32, 32))
        self.label_Mini_knuckles.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_knuckles.setText("")
        self.label_Mini_knuckles.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Knuckles.png"))
        self.label_Mini_knuckles.setScaledContents(True)
        self.label_Mini_knuckles.setObjectName("label_Mini_knuckles")
        self.label_Mini_kernan = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_kernan.setGeometry(QtCore.QRect(40, 70, 32, 32))
        self.label_Mini_kernan.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_kernan.setText("")
        self.label_Mini_kernan.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Kernan.png"))
        self.label_Mini_kernan.setScaledContents(True)
        self.label_Mini_kernan.setObjectName("label_Mini_kernan")
        self.label_Mini_karde = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_karde.setGeometry(QtCore.QRect(70, 70, 32, 32))
        self.label_Mini_karde.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_karde.setText("")
        self.label_Mini_karde.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Karde.png"))
        self.label_Mini_karde.setScaledContents(True)
        self.label_Mini_karde.setObjectName("label_Mini_karde")
        self.label_Mini_slubling = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_slubling.setGeometry(QtCore.QRect(100, 70, 32, 32))
        self.label_Mini_slubling.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_slubling.setText("")
        self.label_Mini_slubling.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Slubling.png"))
        self.label_Mini_slubling.setScaledContents(True)
        self.label_Mini_slubling.setObjectName("label_Mini_slubling")
        self.label_Mini_slothasor = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_slothasor.setGeometry(QtCore.QRect(130, 70, 32, 32))
        self.label_Mini_slothasor.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_slothasor.setText("")
        self.label_Mini_slothasor.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Slothasor.png"))
        self.label_Mini_slothasor.setScaledContents(True)
        self.label_Mini_slothasor.setObjectName("label_Mini_slothasor")
        self.label_Mini_berg = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_berg.setGeometry(QtCore.QRect(10, 100, 32, 32))
        self.label_Mini_berg.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_berg.setText("")
        self.label_Mini_berg.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Berg.png"))
        self.label_Mini_berg.setScaledContents(True)
        self.label_Mini_berg.setObjectName("label_Mini_berg")
        self.label_Mini_qadim = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_qadim.setGeometry(QtCore.QRect(240, 70, 32, 32))
        self.label_Mini_qadim.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_qadim.setText("")
        self.label_Mini_qadim.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Qadim.png"))
        self.label_Mini_qadim.setScaledContents(True)
        self.label_Mini_qadim.setObjectName("label_Mini_qadim")
        self.label_Mini_brokenking = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_brokenking.setGeometry(QtCore.QRect(210, 40, 32, 32))
        self.label_Mini_brokenking.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_brokenking.setText("")
        self.label_Mini_brokenking.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Broken King.png"))
        self.label_Mini_brokenking.setScaledContents(True)
        self.label_Mini_brokenking.setObjectName("label_Mini_brokenking")
        self.label_Mini_dhuum = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_dhuum.setGeometry(QtCore.QRect(240, 40, 32, 32))
        self.label_Mini_dhuum.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_dhuum.setText("")
        self.label_Mini_dhuum.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Dhuum.png"))
        self.label_Mini_dhuum.setScaledContents(True)
        self.label_Mini_dhuum.setObjectName("label_Mini_dhuum")
        self.label_Mini_matthias = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_matthias.setGeometry(QtCore.QRect(100, 100, 32, 32))
        self.label_Mini_matthias.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_matthias.setText("")
        self.label_Mini_matthias.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Matthias Abomination.png"))
        self.label_Mini_matthias.setScaledContents(True)
        self.label_Mini_matthias.setObjectName("label_Mini_matthias")
        self.label_Mini_nikare = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_nikare.setGeometry(QtCore.QRect(210, 70, 32, 32))
        self.label_Mini_nikare.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_nikare.setText("")
        self.label_Mini_nikare.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Nikare.png"))
        self.label_Mini_nikare.setScaledContents(True)
        self.label_Mini_nikare.setObjectName("label_Mini_nikare")
        self.label_Mini_zommoros = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_zommoros.setGeometry(QtCore.QRect(270, 40, 32, 32))
        self.label_Mini_zommoros.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_zommoros.setText("")
        self.label_Mini_zommoros.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Zommoros.png"))
        self.label_Mini_zommoros.setScaledContents(True)
        self.label_Mini_zommoros.setObjectName("label_Mini_zommoros")
        self.label_Mini_kenut = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_kenut.setGeometry(QtCore.QRect(180, 70, 32, 32))
        self.label_Mini_kenut.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_kenut.setText("")
        self.label_Mini_kenut.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Kenut.png"))
        self.label_Mini_kenut.setScaledContents(True)
        self.label_Mini_kenut.setObjectName("label_Mini_kenut")
        self.label_Mini_narella = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_narella.setGeometry(QtCore.QRect(70, 100, 32, 32))
        self.label_Mini_narella.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_narella.setText("")
        self.label_Mini_narella.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Narella.png"))
        self.label_Mini_narella.setScaledContents(True)
        self.label_Mini_narella.setObjectName("label_Mini_narella")
        self.label_Mini_desmina = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_desmina.setGeometry(QtCore.QRect(180, 40, 32, 32))
        self.label_Mini_desmina.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_desmina.setText("")
        self.label_Mini_desmina.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Desmina.png"))
        self.label_Mini_desmina.setScaledContents(True)
        self.label_Mini_desmina.setObjectName("label_Mini_desmina")
        self.label_Mini_zane = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_zane.setGeometry(QtCore.QRect(40, 100, 32, 32))
        self.label_Mini_zane.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_zane.setText("")
        self.label_Mini_zane.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Zane.png"))
        self.label_Mini_zane.setScaledContents(True)
        self.label_Mini_zane.setObjectName("label_Mini_zane")
        self.label_Mini_xera = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_xera.setGeometry(QtCore.QRect(40, 130, 32, 32))
        self.label_Mini_xera.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_xera.setText("")
        self.label_Mini_xera.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Xera.png"))
        self.label_Mini_xera.setScaledContents(True)
        self.label_Mini_xera.setObjectName("label_Mini_xera")
        self.label_Mini_keepconstruct = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_keepconstruct.setGeometry(QtCore.QRect(10, 130, 32, 32))
        self.label_Mini_keepconstruct.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_keepconstruct.setText("")
        self.label_Mini_keepconstruct.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Keep Construct.png"))
        self.label_Mini_keepconstruct.setScaledContents(True)
        self.label_Mini_keepconstruct.setObjectName("label_Mini_keepconstruct")
        self.label_Mini_mcleod = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_mcleod.setGeometry(QtCore.QRect(130, 100, 32, 32))
        self.label_Mini_mcleod.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_mcleod.setText("")
        self.label_Mini_mcleod.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini McLeod the Silent.png"))
        self.label_Mini_mcleod.setScaledContents(True)
        self.label_Mini_mcleod.setObjectName("label_Mini_mcleod")
        self.label_Mini_mursaat = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_mursaat.setGeometry(QtCore.QRect(100, 130, 32, 32))
        self.label_Mini_mursaat.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_mursaat.setText("")
        self.label_Mini_mursaat.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Mursaat Overseer.png"))
        self.label_Mini_mursaat.setScaledContents(True)
        self.label_Mini_mursaat.setObjectName("label_Mini_mursaat")
        self.label_Mini_cairn = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_cairn.setGeometry(QtCore.QRect(70, 130, 32, 32))
        self.label_Mini_cairn.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_cairn.setText("")
        self.label_Mini_cairn.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Cairn the Indomitable.png"))
        self.label_Mini_cairn.setScaledContents(True)
        self.label_Mini_cairn.setObjectName("label_Mini_cairn")
        self.label_Mini_eyeofjanthir = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_eyeofjanthir.setGeometry(QtCore.QRect(130, 130, 32, 32))
        self.label_Mini_eyeofjanthir.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_eyeofjanthir.setText("")
        self.label_Mini_eyeofjanthir.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Eye of Janthir.png"))
        self.label_Mini_eyeofjanthir.setScaledContents(True)
        self.label_Mini_eyeofjanthir.setObjectName("label_Mini_eyeofjanthir")
        self.label_Mini_ragged_whitemantle = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_ragged_whitemantle.setGeometry(QtCore.QRect(70, 160, 32, 32))
        self.label_Mini_ragged_whitemantle.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_ragged_whitemantle.setText("")
        self.label_Mini_ragged_whitemantle.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Ragged White Mantle Figurehead.png"))
        self.label_Mini_ragged_whitemantle.setScaledContents(True)
        self.label_Mini_ragged_whitemantle.setObjectName("label_Mini_ragged_whitemantle")
        self.label_Mini_samarog = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_samarog.setGeometry(QtCore.QRect(10, 160, 32, 32))
        self.label_Mini_samarog.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_samarog.setText("")
        self.label_Mini_samarog.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini Samarog.png"))
        self.label_Mini_samarog.setScaledContents(True)
        self.label_Mini_samarog.setObjectName("label_Mini_samarog")
        self.label_Mini_whitemantle = QtWidgets.QLabel(self.tab_minis)
        self.label_Mini_whitemantle.setGeometry(QtCore.QRect(40, 160, 32, 32))
        self.label_Mini_whitemantle.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Mini_whitemantle.setText("")
        self.label_Mini_whitemantle.setPixmap(QtGui.QPixmap(":/Minis/Images/minis/Mini White Mantle Figurehead.png"))
        self.label_Mini_whitemantle.setScaledContents(True)
        self.label_Mini_whitemantle.setObjectName("label_Mini_whitemantle")
        self.tabUnlocks.addTab(self.tab_minis, "")
        self.tab_skins = QtWidgets.QWidget()
        self.tab_skins.setObjectName("tab_skins")
        self.tabUnlocks.addTab(self.tab_skins, "")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(20, 10, 151, 20))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.botonThemeDefault = QtWidgets.QPushButton(self.centralwidget)
        self.botonThemeDefault.setGeometry(QtCore.QRect(190, 30, 41, 21))
        self.botonThemeDefault.setStyleSheet("background-color: rgb(170, 208, 169);")
        self.botonThemeDefault.setIconSize(QtCore.QSize(20, 20))
        self.botonThemeDefault.setObjectName("botonThemeDefault")
        self.botonThemeLight = QtWidgets.QPushButton(self.centralwidget)
        self.botonThemeLight.setGeometry(QtCore.QRect(270, 30, 41, 21))
        self.botonThemeLight.setStyleSheet("background-color: rgb(170, 208, 169);")
        self.botonThemeLight.setIconSize(QtCore.QSize(20, 20))
        self.botonThemeLight.setObjectName("botonThemeLight")
        self.botonThemeDark = QtWidgets.QPushButton(self.centralwidget)
        self.botonThemeDark.setGeometry(QtCore.QRect(230, 30, 41, 21))
        self.botonThemeDark.setStyleSheet("background-color: rgb(170, 208, 169);")
        self.botonThemeDark.setIconSize(QtCore.QSize(20, 20))
        self.botonThemeDark.setObjectName("botonThemeDark")
        self.botonLanguage_spanish = QtWidgets.QPushButton(self.centralwidget)
        self.botonLanguage_spanish.setGeometry(QtCore.QRect(100, 30, 31, 21))
        self.botonLanguage_spanish.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/Images/Spanish.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonLanguage_spanish.setIcon(icon7)
        self.botonLanguage_spanish.setIconSize(QtCore.QSize(31, 21))
        self.botonLanguage_spanish.setObjectName("botonLanguage_spanish")
        self.botonLanguage_english = QtWidgets.QPushButton(self.centralwidget)
        self.botonLanguage_english.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.botonLanguage_english.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/Images/English.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonLanguage_english.setIcon(icon8)
        self.botonLanguage_english.setIconSize(QtCore.QSize(31, 21))
        self.botonLanguage_english.setObjectName("botonLanguage_english")
        self.label_69 = QtWidgets.QLabel(self.centralwidget)
        self.label_69.setGeometry(QtCore.QRect(170, 10, 151, 20))
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.botonLanguage_french = QtWidgets.QPushButton(self.centralwidget)
        self.botonLanguage_french.setGeometry(QtCore.QRect(60, 30, 31, 21))
        self.botonLanguage_french.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/Images/French.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonLanguage_french.setIcon(icon9)
        self.botonLanguage_french.setIconSize(QtCore.QSize(31, 21))
        self.botonLanguage_french.setObjectName("botonLanguage_french")
        self.botonLanguage_deutsch = QtWidgets.QPushButton(self.centralwidget)
        self.botonLanguage_deutsch.setGeometry(QtCore.QRect(140, 30, 31, 21))
        self.botonLanguage_deutsch.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/Images/Deutsch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonLanguage_deutsch.setIcon(icon10)
        self.botonLanguage_deutsch.setIconSize(QtCore.QSize(31, 21))
        self.botonLanguage_deutsch.setObjectName("botonLanguage_deutsch")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_11.setBuddy(self.linePermission_Unlocks)
        self.label_13.setBuddy(self.linePermission_Tradingpost)
        self.label_15.setBuddy(self.linePermission_Inventories)
        self.label_17.setBuddy(self.linePermission_Characters)
        self.label_18.setBuddy(self.linePermission_Builds)
        self.label_19.setBuddy(self.linePermission_Account)
        self.label_20.setBuddy(self.linePermission_Progression)
        self.label_21.setBuddy(self.linePermission_Guilds)
        self.label_23.setBuddy(self.linePermission_PvP)
        self.label_26.setBuddy(self.linePermission_Wallet)
        self.label_28.setBuddy(self.linePermission_Guilds)
        self.label_29.setBuddy(self.linePermission_Guilds)
        self.label_30.setBuddy(self.linePermission_Guilds)
        self.label_36.setBuddy(self.linePermission_Progression)
        self.label_37.setBuddy(self.linePermission_Progression)
        self.label_40.setBuddy(self.linePermission_PvP)
        self.label_41.setBuddy(self.linePermission_PvP)
        self.label_42.setBuddy(self.linePermission_PvP)
        self.label_43.setBuddy(self.linePermission_PvP)
        self.label_48.setBuddy(self.linePermission_PvP)
        self.label_49.setBuddy(self.linePermission_PvP)
        self.label_50.setBuddy(self.linePermission_PvP)
        self.label_57.setBuddy(self.linePermission_Guilds)
        self.label_58.setBuddy(self.linePermission_Guilds)
        self.label_55.setBuddy(self.linePermission_Guilds)
        self.label_56.setBuddy(self.linePermission_Guilds)
        self.label_59.setBuddy(self.linePermission_Builds)
        self.label_62.setBuddy(self.linePermission_PvP)
        self.label_61.setBuddy(self.linePermission_PvP)
        self.label_64.setBuddy(self.linePermission_PvP)
        self.label_63.setBuddy(self.linePermission_PvP)
        self.label_65.setBuddy(self.linePermission_PvP)
        self.label_60.setBuddy(self.linePermission_PvP)
        self.label_44.setBuddy(self.linePermission_PvP)
        self.label_45.setBuddy(self.linePermission_PvP)
        self.label_81.setBuddy(self.linePermission_PvP)
        self.label_82.setBuddy(self.linePermission_PvP)

        self.retranslateUi(MainWindow)
        self.tabUnlocks.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.linePermission_Account, self.linePermission_Inventories)
        MainWindow.setTabOrder(self.linePermission_Inventories, self.linePermission_Characters)
        MainWindow.setTabOrder(self.linePermission_Characters, self.linePermission_Tradingpost)
        MainWindow.setTabOrder(self.linePermission_Tradingpost, self.linePermission_Wallet)
        MainWindow.setTabOrder(self.linePermission_Wallet, self.linePermission_Unlocks)
        MainWindow.setTabOrder(self.linePermission_Unlocks, self.linePermission_PvP)
        MainWindow.setTabOrder(self.linePermission_PvP, self.linePermission_Builds)
        MainWindow.setTabOrder(self.linePermission_Builds, self.linePermission_Progression)
        MainWindow.setTabOrder(self.linePermission_Progression, self.linePermission_Guilds)
        MainWindow.setTabOrder(self.linePermission_Guilds, self.botonLoad)

    def retranslateUi(self, MainWindow):
        self.groupBossesStatus.setTitle(QtWidgets.QApplication.translate("MainWindow", "RAID BOSSES KILLED THIS WEEK", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Matthias:", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Slothasor:", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Gorseval:", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Sabetha:", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "Keep Construct:", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "Vale Guardian:", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "Xera:", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "Cairn:", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "Escort Glenna:", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "Bandit Trio:", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "Wing 1 - Spirit Vale", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "Mursaat Overseer:", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "Samarog:", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "Deimos:", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "Wing 2 - Salvation Pass", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "Wing 3 - Stronghold of the Faithful", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("MainWindow", "Wing 4 - Bastion of the Penitent", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("MainWindow", "Twisted Castle:", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("MainWindow", "Spirit Woods:", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("MainWindow", "Wing 5 - Hall of Chains", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("MainWindow", "Soulless Horror:", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("MainWindow", "River of Souls:", None, -1))
        self.label_42.setText(QtWidgets.QApplication.translate("MainWindow", "The 3 Statues:", None, -1))
        self.label_43.setText(QtWidgets.QApplication.translate("MainWindow", "Dhuum:", None, -1))
        self.label_47.setText(QtWidgets.QApplication.translate("MainWindow", "Wing 6 - The Mythwright Gambit", None, -1))
        self.label_48.setText(QtWidgets.QApplication.translate("MainWindow", "Twin Largos:", None, -1))
        self.label_49.setText(QtWidgets.QApplication.translate("MainWindow", "Qadim:", None, -1))
        self.label_50.setText(QtWidgets.QApplication.translate("MainWindow", "C. Amalgamated:", None, -1))
        self.label_51.setText(QtWidgets.QApplication.translate("MainWindow", "HEART OF THORNS", None, -1))
        self.label_52.setText(QtWidgets.QApplication.translate("MainWindow", "PATH OF FIRE", None, -1))
        self.label_68.setText(QtWidgets.QApplication.translate("MainWindow", "Wing 7 - (probably around May)", None, -1))
        self.groupChallenges.setTitle(QtWidgets.QApplication.translate("MainWindow", "CHALLENGE MODES COMPLETED", None, -1))
        self.label_57.setText(QtWidgets.QApplication.translate("MainWindow", "Deimos:", None, -1))
        self.label_58.setText(QtWidgets.QApplication.translate("MainWindow", "Samarog:", None, -1))
        self.label_55.setText(QtWidgets.QApplication.translate("MainWindow", "Mursaat:", None, -1))
        self.label_56.setText(QtWidgets.QApplication.translate("MainWindow", "Cairn:", None, -1))
        self.label_59.setText(QtWidgets.QApplication.translate("MainWindow", "Keep Construct:", None, -1))
        self.label_62.setText(QtWidgets.QApplication.translate("MainWindow", "Largos:", None, -1))
        self.label_61.setText(QtWidgets.QApplication.translate("MainWindow", "Qadim:", None, -1))
        self.label_64.setText(QtWidgets.QApplication.translate("MainWindow", "Dhuum:", None, -1))
        self.label_63.setText(QtWidgets.QApplication.translate("MainWindow", "C. Amalgamated:", None, -1))
        self.label_67.setText(QtWidgets.QApplication.translate("MainWindow", "PATH OF FIRE", None, -1))
        self.label_66.setText(QtWidgets.QApplication.translate("MainWindow", "HEART OF THORNS", None, -1))
        self.label_65.setText(QtWidgets.QApplication.translate("MainWindow", "Soulless Horror:", None, -1))
        self.groupArcdps.setTitle(QtWidgets.QApplication.translate("MainWindow", "ARCDPS PLUGIN", None, -1))
        self.label_46.setText(QtWidgets.QApplication.translate("MainWindow", "Guild Wars 2 Installation Folder:", None, -1))
        self.botonArcDps.setText(QtWidgets.QApplication.translate("MainWindow", "Install or Update ArcDps + Build Templates", None, -1))
        self.botonArcDps_mechanics.setText(QtWidgets.QApplication.translate("MainWindow", "Install or Update ArcDps Mechanics Addon", None, -1))
        self.label_53.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">NOTE:</span> Make sure you have the game closed before installing or updating arcdps or mechanics.</p></body></html>", None, -1))
        self.botonLaunchgame.setText(QtWidgets.QApplication.translate("MainWindow", "Launch GW2", None, -1))
        self.botonClosegame.setText(QtWidgets.QApplication.translate("MainWindow", "Close GW2", None, -1))
        self.groupWebsites.setTitle(QtWidgets.QApplication.translate("MainWindow", "USEFUL RAID WEBSITES", None, -1))
        self.botonWebsite_dpsreport.setText(QtWidgets.QApplication.translate("MainWindow", "DPS.Report", None, -1))
        self.botonWebsite_killproof.setText(QtWidgets.QApplication.translate("MainWindow", "Public KillProofs", None, -1))
        self.botonWebsite_raidar.setText(QtWidgets.QApplication.translate("MainWindow", "GW2Raidar", None, -1))
        self.botonWebsite_builds.setText(QtWidgets.QApplication.translate("MainWindow", "Snow Crows Raid Builds", None, -1))
        self.botonWebsite_arcdps.setText(QtWidgets.QApplication.translate("MainWindow", "ArcDps", None, -1))
        self.botonWebsite_arcdpsmechanics.setText(QtWidgets.QApplication.translate("MainWindow", "ArcDps Mechanics", None, -1))
        self.botonWebsite_dulfy.setText(QtWidgets.QApplication.translate("MainWindow", "Dulfy Boss Guides", None, -1))
        self.botonWebsite_builds_alternative.setText(QtWidgets.QApplication.translate("MainWindow", "Metabattle Raid Builds", None, -1))
        self.label_54.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>If you want your website here or want to report a bug, please send an in-game mail to the account <span style=\" font-weight:600;\">Elrey.5472</span> and I will look into it for the next release of this tool.</p></body></html>", None, -1))
        self.label_60.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>TO BE DONE: LANGUAGES, TITLES, ACHIEVEMENTS, SKINS, <br/>Currency earned &quot;this week&quot;, </p></body></html>", None, -1))
        self.groupCurrency.setTitle(QtWidgets.QApplication.translate("MainWindow", "RAID CURRENCY", None, -1))
        self.label_93.setText(QtWidgets.QApplication.translate("MainWindow", "PATH OF FIRE", None, -1))
        self.label_94.setText(QtWidgets.QApplication.translate("MainWindow", "HEART OF THORNS", None, -1))
        self.label_44.setText(QtWidgets.QApplication.translate("MainWindow", "Magnetite Shards:", None, -1))
        self.label_45.setText(QtWidgets.QApplication.translate("MainWindow", "Gaeting Crystals:", None, -1))
        self.label_81.setText(QtWidgets.QApplication.translate("MainWindow", "Legendary Divinations:", None, -1))
        self.label_82.setText(QtWidgets.QApplication.translate("MainWindow", "Legendary Insights (LIs):", None, -1))
        self.label_70.setText(QtWidgets.QApplication.translate("MainWindow", "This week", None, -1))
        self.label_71.setText(QtWidgets.QApplication.translate("MainWindow", "This week", None, -1))
        self.label_72.setText(QtWidgets.QApplication.translate("MainWindow", "Total", None, -1))
        self.label_73.setText(QtWidgets.QApplication.translate("MainWindow", "Total", None, -1))
        self.groupAPI.setTitle(QtWidgets.QApplication.translate("MainWindow", "API KEY, PERMISSIONS AND OPTIONS", None, -1))
        self.botonWebsite_Anet.setText(QtWidgets.QApplication.translate("MainWindow", "Get API", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "SELECTED API KEY", None, -1))
        self.botonLoad.setText(QtWidgets.QApplication.translate("MainWindow", "Load data", None, -1))
        self.botonDeleteAPI.setText(QtWidgets.QApplication.translate("MainWindow", "Delete API", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">You can create API keys at the Guild Wars 2 website.<br/>* </span>Your API key will be able to <span style=\" font-weight:600;\">only read</span> and provide information from the Guild Wars 2 servers, but it can\'t edit, change or update anything for your account.</p></body></html>", None, -1))
        self.botonAddAPI.setText(QtWidgets.QApplication.translate("MainWindow", "Add new API", None, -1))
        self.linePermission_Characters.setText(QtWidgets.QApplication.translate("MainWindow", "Characters", None, -1))
        self.linePermission_Guilds.setText(QtWidgets.QApplication.translate("MainWindow", "Guilds", None, -1))
        self.linePermission_PvP.setText(QtWidgets.QApplication.translate("MainWindow", "PvP", None, -1))
        self.linePermission_Unlocks.setText(QtWidgets.QApplication.translate("MainWindow", "Unlocks", None, -1))
        self.linePermission_Builds.setText(QtWidgets.QApplication.translate("MainWindow", "Builds", None, -1))
        self.linePermission_Tradingpost.setText(QtWidgets.QApplication.translate("MainWindow", "Trading Post", None, -1))
        self.linePermission_Inventories.setText(QtWidgets.QApplication.translate("MainWindow", "Inventories", None, -1))
        self.linePermission_Progression.setText(QtWidgets.QApplication.translate("MainWindow", "Progression", None, -1))
        self.linePermission_Wallet.setText(QtWidgets.QApplication.translate("MainWindow", "Wallet", None, -1))
        self.linePermission_Account.setText(QtWidgets.QApplication.translate("MainWindow", "Account", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("MainWindow", "PERMISSIONS OF THAT KEY:", None, -1))
        self.label_92.setText(QtWidgets.QApplication.translate("MainWindow", "HEART OF THORNS", None, -1))
        self.label_91.setText(QtWidgets.QApplication.translate("MainWindow", "PATH OF FIRE", None, -1))
        self.tabUnlocks.setTabText(self.tabUnlocks.indexOf(self.tab_minis), QtWidgets.QApplication.translate("MainWindow", "Minis", None, -1))
        self.tabUnlocks.setTabText(self.tabUnlocks.indexOf(self.tab_skins), QtWidgets.QApplication.translate("MainWindow", "Skins", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("MainWindow", "LANGUAGES", None, -1))
        self.botonThemeDefault.setText(QtWidgets.QApplication.translate("MainWindow", "Gray", None, -1))
        self.botonThemeLight.setText(QtWidgets.QApplication.translate("MainWindow", "Blue", None, -1))
        self.botonThemeDark.setText(QtWidgets.QApplication.translate("MainWindow", "Dark", None, -1))
        self.label_69.setText(QtWidgets.QApplication.translate("MainWindow", "THEMES & COLORS", None, -1))

import resources_rc
